# .github/workflows/ci.yml
name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --exclude=venv,.git --show-source --statistics
        flake8 . --count --max-complexity=10 --max-line-length=99 --exclude=venv,.git --statistics

    - name: Run a simple script (CI check)
      run: |
        python -c "import database; print('Database imported successfully.')"
        python -c "import main; print('FastAPI app imported successfully.')"
